### ISSUE TITLE
Iteration Plan for July 22, 2019 (Discord-UI v2.1.2)

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#40]
![icon_40](https://user-images.githubusercontent.com/31692408/60932195-d410bf80-a2f7-11e9-9db4-0dac6d3261f9.gif)
Announcement of the plan for July 22, 2019.

## Schedule
- [x] **July 13, 2019**: Fixed Discord UI images and testing in-game
- [x] **July 14, 2019**: Commit all UI dds in SHADOWBRINGER & distribute Material UI (Discord)
- [x] **July 15-22, 2019**: Correct focused bugs(or enhancement) based on feedback / Distribution

## FAQ
- **_When will the black version be released?_**
I'm very sorry if you're waiting for the black version. After the launch of Material UI(Discord), I will prepare for the "Eden Raid". Therefore, I will temporarily suspend development until the middle of August.

## Feedback
- [x] Transparency for unselected windows #39 @noxxxiie [Support as an option]
- [x] Levequest DoH/DoL icon #41 @skotlex 
- [x] <s>Delete line</s> Change crafting delimiter color and position #42 @skotlex 
- [x] Remove background of macro paging icon #43 @skotlex 
- [x] Broken right border of quest complete dialog #44 @skotlex 
- [x] Gunbreaker and Dancer have different glow #45 @nellieh
- [x] Colour the limit break bar similar to original #46 @insarius
- [x] Background on jobs icon in the desynthesis menu #47 @Vayhyr [Support as an option]

**Comment by noxxxiie** [comment]
3 types of transperncy like 25 50 and 75 % would be a nice options in both black and Discord themes

**Comment by skotlex** [comment]
I think it's a little wasteful to make three options with only % of transparency being different. I'll aim to make it look like the screen shot I posted earlier. Please understand this point.

**Comment by skotlex** [comment]
@noxxxiie This is how it's going to change.

![changelog_03](https://user-images.githubusercontent.com/31692408/61576218-2d57ca80-ab12-11e9-94a8-f669d5bd799c.png)
